# Generated by Django 6.0.4 on 2026-04-22 12:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_seed',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
