# Generated by Django 6.0.4 on 2026-04-21 01:51

from django.db import migrations, models


def move_blocked_jobs_to_unassigned(apps, schema_editor):
    job = apps.get_model("jobs", "Job")
    historical_job = apps.get_model("jobs", "HistoricalJob")
    job.objects.filter(status="blocked").update(status="unassigned")
    historical_job.objects.filter(status="blocked").update(status="unassigned")


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljob',
            name='cancelled_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='cancelled_reason',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(move_blocked_jobs_to_unassigned, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='historicaljob',
            name='status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('planned', 'Planned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='unassigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('planned', 'Planned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='unassigned', max_length=20),
        ),
    ]
