# Generated by Django 6.0.4 on 2026-05-05 08:44

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_rename_cancelled_reason_closeout_note"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="jobtemplate",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("title"),
                name="unique_job_template_title_case_insensitive",
            ),
        ),
    ]
