# Generated by Django 6.0.4 on 2026-05-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_historicaljob_cancelled_reason_job_cancelled_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljob',
            name='status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='unassigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='unassigned', max_length=20),
        ),
    ]
