# Generated by Django 6.0.4 on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_historicalworkprogramme_workprogramme_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalworkprogramme",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalworkprogramme",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workprogramme",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workprogramme",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
