# Generated by Django 6.0.4 on 2026-04-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitevisit',
            options={'ordering': ['trip', 'planned_start', 'planned_order', 'site__code']},
        ),
        migrations.AddField(
            model_name='historicalsitevisit',
            name='planned_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsitevisit',
            name='planned_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='planned_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='planned_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsitevisit',
            name='planned_order',
            field=models.PositiveIntegerField(default=1, verbose_name='Sequence'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='planned_order',
            field=models.PositiveIntegerField(default=1, verbose_name='Sequence'),
        ),
    ]
