# Generated by Django 6.0.4 on 2026-04-21 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_sitevisit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitevisit',
            options={'ordering': ['trip', 'planned_start', 'site__code', 'id']},
        ),
        migrations.RemoveField(
            model_name='historicalsitevisit',
            name='planned_order',
        ),
        migrations.RemoveField(
            model_name='sitevisit',
            name='planned_order',
        ),
    ]
