from django.contrib.auth.mixins import LoginRequiredMixin

from .action_views import (
    approve_trip_view,
    assign_job,
    cancel_trip_view,
    close_trip_view,
    correct_trip_closeout_view,
    return_trip_to_draft_view,
    submit_trip_view,
    unassign_job,
)
from .detail_views import (
    SiteVisitCreateView,
    SiteVisitDeleteView,
    SiteVisitDetailView,
    SiteVisitHistoryDetailView,
    SiteVisitHistoryView,
    SiteVisitUpdateView,
    TripCreateView,
    TripDetailView,
    TripHistoryDetailView,
    TripHistoryView,
    TripMapView,
    TripRequirementCreateView,
    TripRequirementDeleteView,
    TripRequirementsView,
    TripRequirementUpdateView,
    TripUpdateView,
    toggle_trip_requirement,
)
from .list_views import TripGanttView, TripListView

__all__ = [
    "LoginRequiredMixin",
    "TripListView",
    "TripGanttView",
    "TripDetailView",
    "TripMapView",
    "TripRequirementsView",
    "TripRequirementCreateView",
    "TripRequirementUpdateView",
    "TripRequirementDeleteView",
    "TripHistoryView",
    "TripHistoryDetailView",
    "TripCreateView",
    "TripUpdateView",
    "SiteVisitDetailView",
    "SiteVisitDeleteView",
    "SiteVisitHistoryView",
    "SiteVisitHistoryDetailView",
    "SiteVisitCreateView",
    "SiteVisitUpdateView",
    "assign_job",
    "unassign_job",
    "submit_trip_view",
    "approve_trip_view",
    "return_trip_to_draft_view",
    "close_trip_view",
    "correct_trip_closeout_view",
    "cancel_trip_view",
    "toggle_trip_requirement",
]
