# Generated by Django 6.0.4 on 2026-04-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsite',
            name='heli_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalsite',
            name='road_end_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='historicalsite',
            name='road_end_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='heli_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='road_end_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='road_end_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
