# Generated by Django 6.0.4 on 2026-05-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_historicalsitephoto_sitephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsitephoto',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsitephoto',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitephoto',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitephoto',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
