# Generated by Django 6.0.4 on 2026-04-25 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_accessrecord_historicalaccessrecord_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsite',
            old_name='road_end_latitude',
            new_name='access_start_latitude',
        ),
        migrations.RenameField(
            model_name='historicalsite',
            old_name='road_end_longitude',
            new_name='access_start_longitude',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='road_end_latitude',
            new_name='access_start_latitude',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='road_end_longitude',
            new_name='access_start_longitude',
        ),
        migrations.RemoveField(
            model_name='historicalsite',
            name='heli_only',
        ),
        migrations.RemoveField(
            model_name='site',
            name='heli_only',
        ),
    ]
