# Generated by Django 6.0.4 on 2026-04-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_rename_road_end_latitude_historicalsite_access_start_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsite',
            name='sync_status',
            field=models.CharField(choices=[('active', 'Active'), ('stale', 'Stale')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='site',
            name='sync_status',
            field=models.CharField(choices=[('active', 'Active'), ('stale', 'Stale')], default='active', max_length=20),
        ),
    ]
