# Generated by Django 6.0.4 on 2026-05-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_historicalsitephoto_image_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsite',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='site',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
