# Generated by Django 6.0.4 on 2026-04-26 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0005_historicalsite_sync_status_site_sync_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accessrecord",
            options={"ordering": ["site__code", "name"]},
        ),
        migrations.AddField(
            model_name="accessrecord",
            name="access_type",
            field=models.CharField(
                choices=[
                    ("road", "Road"),
                    ("boat", "Boat"),
                    ("heli", "Heli"),
                    ("walking", "Walking"),
                    ("other", "Other"),
                ],
                default="road",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="accessrecord",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="accessrecord",
            name="name",
            field=models.CharField(default="Access record", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalaccessrecord",
            name="access_type",
            field=models.CharField(
                choices=[
                    ("road", "Road"),
                    ("boat", "Boat"),
                    ("heli", "Heli"),
                    ("walking", "Walking"),
                    ("other", "Other"),
                ],
                default="road",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicalaccessrecord",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalaccessrecord",
            name="name",
            field=models.CharField(default="Access record", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="accessrecord",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_records",
                to="sites.site",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessrecord",
            constraint=models.UniqueConstraint(
                fields=("site", "name"), name="unique_access_record_name_per_site"
            ),
        ),
    ]
