# Generated by Django 6.0.4 on 2026-04-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0006_alter_accessrecord_options_accessrecord_access_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accessrecord",
            old_name="access_type",
            new_name="arrival_method",
        ),
        migrations.RenameField(
            model_name="historicalaccessrecord",
            old_name="access_type",
            new_name="arrival_method",
        ),
        migrations.RenameField(
            model_name="accessrecord",
            old_name="is_active",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="historicalaccessrecord",
            old_name="is_active",
            new_name="status",
        ),
        migrations.AlterField(
            model_name="accessrecord",
            name="arrival_method",
            field=models.CharField(
                choices=[
                    ("road", "Road"),
                    ("boat", "Boat"),
                    ("heli", "Heli"),
                    ("other", "Other"),
                ],
                default="road",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalaccessrecord",
            name="arrival_method",
            field=models.CharField(
                choices=[
                    ("road", "Road"),
                    ("boat", "Boat"),
                    ("heli", "Heli"),
                    ("other", "Other"),
                ],
                default="road",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="accessrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("retired", "Retired"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalaccessrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("retired", "Retired"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
