# Generated by Django 6.0.4 on 2026-04-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_rename_access_record_metadata_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrecord',
            name='arrival_method',
            field=models.CharField(choices=[('road', 'Road'), ('boat', 'Boat'), ('heli', 'Helicopter'), ('other', 'Other')], default='road', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalaccessrecord',
            name='arrival_method',
            field=models.CharField(choices=[('road', 'Road'), ('boat', 'Boat'), ('heli', 'Helicopter'), ('other', 'Other')], default='road', max_length=20),
        ),
    ]
