# Generated by Django 6.0.4 on 2026-05-01 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_accessrecorduploaddraft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsite',
            name='access_start_latitude',
        ),
        migrations.RemoveField(
            model_name='historicalsite',
            name='access_start_longitude',
        ),
        migrations.RemoveField(
            model_name='site',
            name='access_start_latitude',
        ),
        migrations.RemoveField(
            model_name='site',
            name='access_start_longitude',
        ),
    ]
